"""
Multimodal RAG: Retrieval over documents that contain both text and images.

Two common patterns:
  1. Captioning: convert images/pages to text descriptions, index the captions
  2. Vision embeddings: embed page images directly (e.g., ColPali)

This demo shows the captioning pattern using synthetic image descriptions
so it runs offline without a vision model or API key.
The logic is identical to a production system — only the caption source differs.
"""

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# ── Document corpus: text chunks + image captions ────────────────────────────
# In production: images are processed by a vision model (GPT-4V, LLaVA, etc.)
# to generate captions. Here captions are written manually.

documents = [
    # Text chunks
    {"id": "t1", "type": "text",    "content": "Nike's revenue in fiscal 2023 was $51.2 billion, up 10 percent year-over-year."},
    {"id": "t2", "type": "text",    "content": "Nike is committed to reducing its carbon footprint by 70 percent by 2025."},
    {"id": "t3", "type": "text",    "content": "Nike employs approximately 79,000 people worldwide."},
    # Image captions (generated by vision model in production)
    {"id": "img1", "type": "image", "content": "Bar chart showing Nike revenue by quarter: Q1=$12.4B, Q2=$12.8B, Q3=$12.9B, Q4=$13.1B. Total fiscal 2023 revenue $51.2B.", "source": "page_4_chart.png"},
    {"id": "img2", "type": "image", "content": "Pie chart showing Nike product category breakdown: Footwear 66%, Apparel 28%, Equipment 6%.", "source": "page_7_chart.png"},
    {"id": "img3", "type": "image", "content": "Line graph showing Nike carbon emissions reduction from 2015 to 2023, with target line at 70% reduction by 2025.", "source": "page_12_sustainability.png"},
    {"id": "img4", "type": "image", "content": "World map showing Nike manufacturing locations: Vietnam 50%, Indonesia 27%, China 18%, other 5%.", "source": "page_15_supply_chain.png"},
]

model = SentenceTransformer("all-MiniLM-L6-v2")
contents = [d["content"] for d in documents]
embs = model.encode(contents).astype("float32")
faiss.normalize_L2(embs)
index = faiss.IndexFlatIP(embs.shape[1])
index.add(embs)


def multimodal_retrieve(query: str, k: int = 3) -> list:
    q_emb = model.encode([query]).astype("float32")
    faiss.normalize_L2(q_emb)
    scores, idx = index.search(q_emb, k)
    return [(documents[i], float(s)) for i, s in zip(idx[0], scores[0])]


queries = [
    "What was Nike's quarterly revenue breakdown?",
    "What is Nike's sustainability commitment?",
    "Where does Nike manufacture its products?",
]

for query in queries:
    results = multimodal_retrieve(query)
    print(f"Query: '{query}'")
    for doc, score in results:
        source = doc.get("source", "text")
        print(f"  [{score:.3f}] [{doc['type']:5}] {doc['content'][:80]}")
        if doc["type"] == "image":
            print(f"           Source: {source}")
    print()


# Output:
# Query: 'What was Nike's quarterly revenue breakdown?'
#   [0.812] [image] Bar chart showing Nike revenue by quarter: Q1=$12.4B, Q2=$12.8B...
#            Source: page_4_chart.png
#   [0.634] [text ] Nike's revenue in fiscal 2023 was $51.2 billion, up 10 percent...
#   [0.521] [image] Pie chart showing Nike product category breakdown: Footwear 66%...
#            Source: page_7_chart.png
#
# Query: 'What is Nike's sustainability commitment?'
#   [0.823] [text ] Nike is committed to reducing its carbon footprint by 70 percent...
#   [0.756] [image] Line graph showing Nike carbon emissions reduction from 2015 to 2023...
#            Source: page_12_sustainability.png
#   [0.412] [text ] Nike employs approximately 79,000 people worldwide.
#
# Query: 'Where does Nike manufacture its products?'
#   [0.891] [image] World map showing Nike manufacturing locations: Vietnam 50%...
#            Source: page_15_supply_chain.png
#   [0.423] [text ] Nike employs approximately 79,000 people worldwide.
#   [0.312] [text ] Nike's revenue in fiscal 2023 was $51.2 billion...

# Findings:
# Image captions are indexed and retrieved exactly like text chunks — the
# retriever does not need to know whether content came from text or an image.
# The quarterly revenue query retrieves the bar chart (image) as rank 1 —
# this information exists only in the chart, not in any text chunk.
# The manufacturing query retrieves only the world map image — this data
# is entirely visual and would be missed by text-only RAG.
# In production: use GPT-4V, LLaVA, or ColPali to generate captions.
# Always store the source image path so the LLM can cite the original figure.
