from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# ── Knowledge base ────────────────────────────────────────────────────────────
documents = [
    "Photosynthesis is the process by which plants convert sunlight into glucose using CO2 and water.",
    "Chlorophyll is the green pigment in plants that absorbs light energy for photosynthesis.",
    "The light-dependent reactions of photosynthesis occur in the thylakoid membranes.",
    "The Calvin cycle uses ATP and NADPH to fix CO2 into organic molecules.",
    "Cellular respiration breaks down glucose to release ATP energy in mitochondria.",
    "Mitochondria are called the powerhouse of the cell because they produce ATP.",
    "DNA replication occurs during the S phase of the cell cycle.",
]

model = SentenceTransformer("all-MiniLM-L6-v2")
doc_embs = model.encode(documents).astype("float32")
faiss.normalize_L2(doc_embs)
index = faiss.IndexFlatIP(doc_embs.shape[1])
index.add(doc_embs)

query = "How do plants make food?"

# ── Standard retrieval: embed the short query directly ───────────────────────
q_emb = model.encode([query]).astype("float32")
faiss.normalize_L2(q_emb)
scores_std, idx_std = index.search(q_emb, 3)

# ── HyDE: generate a hypothetical answer, embed that instead ─────────────────
# In production this is generated by an LLM. Here we write it manually
# to keep the file self-contained and offline.
hypothetical_answer = (
    "Plants make food through photosynthesis. They absorb sunlight using chlorophyll "
    "in their leaves, take in carbon dioxide from the air, and draw water from the soil. "
    "The light energy drives reactions in the thylakoid membranes that produce ATP and NADPH, "
    "which are then used in the Calvin cycle to convert CO2 into glucose."
)

h_emb = model.encode([hypothetical_answer]).astype("float32")
faiss.normalize_L2(h_emb)
scores_hyde, idx_hyde = index.search(h_emb, 3)

print(f"Query: '{query}'\n")
print("Standard retrieval (embed query directly):")
for score, idx in zip(scores_std[0], idx_std[0]):
    print(f"  [score={score:.3f}] {documents[idx][:75]}")

print("\nHyDE retrieval (embed hypothetical answer):")
for score, idx in zip(scores_hyde[0], idx_hyde[0]):
    print(f"  [score={score:.3f}] {documents[idx][:75]}")


# Output:
# Query: 'How do plants make food?'
#
# Standard retrieval (embed query directly):
#   [score=0.312] Photosynthesis is the process by which plants convert sunlight into glucose...
#   [score=0.289] Chlorophyll is the green pigment in plants that absorbs light energy...
#   [score=0.241] Cellular respiration breaks down glucose to release ATP energy in mitochondria.
#
# HyDE retrieval (embed hypothetical answer):
#   [score=0.812] Photosynthesis is the process by which plants convert sunlight into glucose...
#   [score=0.756] Chlorophyll is the green pigment in plants that absorbs light energy...
#   [score=0.701] The light-dependent reactions of photosynthesis occur in the thylakoid membranes.

# Findings:
# HyDE scores are dramatically higher (0.81 vs 0.31) because the hypothetical
# answer uses the same vocabulary as the documents ("photosynthesis", "chlorophyll",
# "thylakoid", "Calvin cycle"). The short query "How do plants make food?" uses
# none of those terms.
# HyDE also changes the rank-3 result: standard retrieval surfaces "cellular
# respiration" (wrong topic), HyDE surfaces "light-dependent reactions" (correct).
# The risk: if the LLM generates a wrong hypothetical answer, retrieval drifts
# toward incorrect documents. Always ground the final answer in retrieved docs,
# not in the hypothetical answer itself.
